spring:
  application:
    name: file-service
    
  profiles:
    active: dev

date-format: "2006-01-02"
date-time-format: "2006-01-02 15:04:05.000"
time-zone: Asia/Shanghai
   
server:
  port: 6103

logging:
  level: debug
  file: logs/file-service.log
  date-time-format: "2006-01-02 15:04:05.000"

nacos:
  namespace: 0c9a8343-cf65-4bc1-804f-497d36237a5f
  host: 127.0.0.1
  port: 8848
  context-path: nacos
  group: DEFAULT_GROUP
  username: dev
  password: Ju*9O7Fx(1WFujhP