spring:
  application:
    name: file-service
    
  profiles:
    active: dev

date-format: "2006-01-02"
date-time-format: "2006-01-02 15:04:05.000"
time-zone: Asia/Shanghai
   
server:
  port: 6103

logging:
  level: debug
  file: logs/file-service.log
  date-time-format: "2006-01-02 15:04:05.000"

nacos:
  namespace: 50e0796d-9008-4378-a5cb-32d9ff0a616a
  host: 192.168.1.161
  port: 8848
  context-path: nacos
  group: DEFAULT_GROUP
  username: dev
  password: Dev@2024
